export const THEMES = {
  blue: {
    id: 'blue',
    name: '经典蓝',
    desc: '清爽专业',
    primary: '#4f8cff',
    primaryDark: '#3a6fd8',
    primaryLight: '#eef3ff',
    primarySoft: '#dbeafe',
    gradient: 'linear-gradient(135deg, #4f8cff 0%, #6c5ce7 100%)',
    gradientSoft: 'linear-gradient(180deg, #eef3ff 0%, #f5f7fb 55%)',
    accent: '#6c5ce7',
    bg: '#f5f7fb',
    card: '#ffffff',
    text: '#0f172a',
    textSecondary: '#64748b',
    textMuted: '#94a3b8',
    border: '#e2e8f0',
    inputBg: '#f8fafc',
    success: '#10b981',
    successBg: '#ecfdf5',
    warning: '#f59e0b',
    warningBg: '#fffbeb',
    danger: '#ef4444',
    dangerBg: '#fef2f2',
    navBg: '#ffffff',
    shadow: '0 8rpx 32rpx rgba(79, 140, 255, 0.08)',
    tabInactive: '#64748b',
  },
  orange: {
    id: 'orange',
    name: '活力橙',
    desc: '温暖明亮',
    primary: '#ff8c42',
    primaryDark: '#e56a1a',
    primaryLight: '#fff4eb',
    primarySoft: '#ffe4cc',
    gradient: 'linear-gradient(135deg, #ff8c42 0%, #ff6b35 100%)',
    gradientSoft: 'linear-gradient(180deg, #fff4eb 0%, #faf8f6 55%)',
    accent: '#ff6b35',
    bg: '#faf8f6',
    card: '#ffffff',
    text: '#1c1917',
    textSecondary: '#78716c',
    textMuted: '#a8a29e',
    border: '#e7e5e4',
    inputBg: '#fafaf9',
    success: '#10b981',
    successBg: '#ecfdf5',
    warning: '#f59e0b',
    warningBg: '#fffbeb',
    danger: '#ef4444',
    dangerBg: '#fef2f2',
    navBg: '#ffffff',
    shadow: '0 8rpx 32rpx rgba(255, 140, 66, 0.1)',
    tabInactive: '#78716c',
  },
}

export function themeToCssVars(theme) {
  return {
    '--c-primary': theme.primary,
    '--c-primary-dark': theme.primaryDark,
    '--c-primary-light': theme.primaryLight,
    '--c-primary-soft': theme.primarySoft,
    '--c-gradient': theme.gradient,
    '--c-gradient-soft': theme.gradientSoft,
    '--c-accent': theme.accent,
    '--c-bg': theme.bg,
    '--c-card': theme.card,
    '--c-text': theme.text,
    '--c-text-secondary': theme.textSecondary,
    '--c-text-muted': theme.textMuted,
    '--c-border': theme.border,
    '--c-input-bg': theme.inputBg,
    '--c-success': theme.success,
    '--c-success-bg': theme.successBg,
    '--c-warning': theme.warning,
    '--c-warning-bg': theme.warningBg,
    '--c-danger': theme.danger,
    '--c-danger-bg': theme.dangerBg,
    '--c-nav-bg': theme.navBg,
    '--c-shadow': theme.shadow,
    '--c-tab-inactive': theme.tabInactive,
  }
}
