/** 竖屏叠层消除 · 底部槽位三消 · 藏 3 颗炸弹 */
const LEVELS = [
  {
    id: 1,
    name: '新手试炼',
    desc: '18 块 · 1 层',
    tileCount: 18,
    layers: 1,
    gridCols: 5,
    gridRows: 4,
    tileSize: 92,
    accent: '#FFB74D',
    accentDark: '#E65100',
    bgm: 'warm',
  },
  {
    id: 2,
    name: '水果海啸',
    desc: '60 块 · 4 层',
    tileCount: 60,
    layers: 4,
    gridCols: 5,
    gridRows: 3,
    tileSize: 58,
    accent: '#FFA726',
    accentDark: '#EF6C00',
    bgm: 'warm',
  },
  {
    id: 3,
    name: '密集阵列',
    desc: '180 块 · 11 层',
    tileCount: 180,
    layers: 11,
    gridCols: 6,
    gridRows: 10,
    tileSize: 36,
    accent: '#42A5F5',
    accentDark: '#1565C0',
    bgm: 'warm',
  },
  {
    id: 4,
    name: '地狱模式',
    desc: '240 块 · 14 层',
    tileCount: 240,
    layers: 14,
    gridCols: 7,
    gridRows: 11,
    tileSize: 32,
    accent: '#AB47BC',
    accentDark: '#6A1B9A',
    bgm: 'warm',
  },
  {
    id: 5,
    name: '不可能',
    desc: '300 块 · 17 层',
    tileCount: 300,
    layers: 17,
    gridCols: 7,
    gridRows: 12,
    tileSize: 28,
    accent: '#EF5350',
    accentDark: '#C62828',
    bgm: 'warm',
  },
  {
    id: 6,
    name: '噩梦筛查',
    desc: '360 块 · 20 层',
    tileCount: 360,
    layers: 20,
    gridCols: 7,
    gridRows: 13,
    tileSize: 26,
    accent: '#5C6BC0',
    accentDark: '#283593',
    bgm: 'warm',
  },
  {
    id: 7,
    name: '终极地狱',
    desc: '420 块 · 24 层',
    tileCount: 420,
    layers: 24,
    gridCols: 8,
    gridRows: 14,
    tileSize: 24,
    accent: '#212121',
    accentDark: '#000000',
    bgm: 'warm',
  },
];

export default LEVELS;

export function getLevel(id) {
  return LEVELS.find((l) => l.id === id) || LEVELS[0];
}
