export default {
  title: '噬魂荒原',
  subtitle: '',
  hudHeight: 0.09,
  actionBarHeight: 0.11,
  winPower: 10000000000,
  moveThreshold: 100,
  world: {
    width: 1400000,
    height: 1400000,
    gridStep: 120,
    spawnRatio: 0.05,
    initialRadius: 15000,
  },
  player: {
    baseSpeed: 3.4,
    minRadius: 16,
    radiusScale: 3.2,
  },
  spawner: {
    maxAlive: 115,
    interval: 36,
    cullDist: 3600,
    spawnMin: 340,
    spawnMax: 820,
    minBeatables: 7,
    beatableRadius: 750,
  },
  skills: [
    {
      id: 'rush',
      name: '加速',
      short: '速',
      unlockPower: 30000,
      cost: 50000,
      cooldown: 200,
      duration: 150,
      speedMul: 3.2,
      color: '#FFD54F',
    },
    {
      id: 'magnet',
      name: '吸魂',
      short: '吸',
      unlockPower: 10000,
      cost: 8000,
      cooldown: 180,
      duration: 120,
      pullRadius: 520,
      color: '#BA68C8',
    },
    {
      id: 'shock',
      name: '震爆',
      short: '震',
      unlockPower: 80000,
      cost: 30000,
      cooldown: 280,
      gridRadius: 6,
      color: '#FF8A65',
    },
    {
      id: 'purge',
      name: '炼狱',
      short: '炼',
      unlockPower: 500000,
      cost: 200000,
      cooldown: 520,
      gridRadius: 14,
      color: '#EF5350',
    },
  ],
  weapons: [
    {
      id: 'range',
      name: '扩域',
      short: '域',
      unlockPower: 5000,
      rangeMul: 1.45,
      color: '#81C784',
    },
    {
      id: 'wheel',
      name: '金轮',
      short: '轮',
      unlockPower: 80000,
      orbitRadius: 72,
      hitRadius: 28,
      orbitSpeed: 0.1,
      count: 3,
      color: '#FFD54F',
    },
    {
      id: 'ice',
      name: '寒冰',
      short: '冰',
      unlockPower: 300000,
      auraRadius: 220,
      slowFactor: 0.38,
      color: '#4FC3F7',
    },
    {
      id: 'fire',
      name: '烈焰',
      short: '焰',
      unlockPower: 1500000,
      burnRadius: 200,
      burnInterval: 40,
      color: '#FF7043',
    },
  ],
  assets: {
    menuBg: 'images/menu_bg.png',
    tileGround: 'images/tile_ground.png',
    player: 'images/player_hero.png',
    enemy: 'images/enemy_ghost.png',
    boss: 'images/boss_lord.png',
    terrain: {
      tree: 'images/terrain_tree.png',
      rock: 'images/terrain_rock.png',
      bone: 'images/terrain_bone.png',
      grave: 'images/terrain_grave.png',
      ruin: 'images/terrain_ruin.png',
    },
    audio: {
      bgm: 'audio/bgm.mp3',
      absorb: 'audio/bullet.mp3',
      die: 'audio/boom.mp3',
      win: 'audio/upgrade.mp3',
    },
  },
  modes: {
    normal: {
      id: 'normal',
      name: '普通模式',
      desc: '',
      accent: '#7E57C2',
      accentDark: '#4527A0',
      startPower: 1,
      enemyCount: 90,
      seed: 101,
    },
    extreme: {
      id: 'extreme',
      name: '极限模式',
      desc: '',
      accent: '#EF5350',
      accentDark: '#B71C1C',
      startPower: 'saved',
      enemyCount: 110,
      seed: 202,
      mobileRate: 0.65,
      strongRate: 0.22,
      infinite: true,
    },
  },
};
