/** 本地存档键名 */
export const STORAGE_KEYS = {
  MONEY: 'MC_MONEY',
  MOVE_TRACK: 'MC_MOVE_TRACK',
  USER_POSITION: 'MC_USER_POSITION',
  WORLD_ORES: 'MC_WORLD_ORES',
  MAX_DEPTH: 'MC_MAX_DEPTH',
  TOTAL_COLLECTED: 'MC_TOTAL_COLLECTED',
  UPGRADES: 'MC_UPGRADES',
  /** 已卸下装备（categoryId → true 表示不生效） */
  DISABLED_UPGRADES: 'MC_DISABLED_UPGRADES',
  DIAMONDS: 'MC_DIAMONDS',
  GACHA_PITY: 'MC_GACHA_PITY',
}

export default STORAGE_KEYS
